// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/posts/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/posts/:id";
  };
  "pages/home/Home.tsx": {
    id: "pages/home/Home";
    page: "/";
  };
  "pages/posts/Post.tsx": {
    id: "pages/posts/Post";
    page: "/posts/:id";
  };
};