 name: Build and Deploy to R2                                                                                          
                                                                                                                       
 on:                                                                                                                   
   push:                                                                                                               
     branches: [main]                                                                                                  
   workflow_dispatch:                                                                                                  
                                                                                                                       
 jobs:                                                                                                                 
   build-and-deploy:                                                                                                   
     runs-on: ubuntu-latest                                                                                            
                                                                                                                       
     steps:                                                                                                            
       - name: Checkout code                                                                                           
         uses: actions/checkout@v3                                                                                     
         with:                                                                                                         
           fetch-depth: 0                                                                                              
                                                                                                                       
       - name: Install Nix                                                                                             
         uses: cachix/install-nix-action@v22                                                                           
         with:                                                                                                         
           nix_path: nixpkgs=channel:nixos-unstable                                                                    
           extra_nix_config: |                                                                                         
             experimental-features = nix-command flakes                                                                
                                                                                                                       
       - name: Build website                                                                                           
         run: |                                                                                                        
           WEBSITE_OUTPUT=$(nix build --print-out-paths)                                                               
           echo "WEBSITE_OUTPUT=$WEBSITE_OUTPUT" >> $GITHUB_ENV                                                        
                                                                                                                       
       - name: Install s3deploy                                                                                        
         run: |                                                                                                        
           curl -L https://github.com/bep/s3deploy/releases/download/v2.5.1/s3deploy_2.5.1_Linux-64bit.tar.gz | tar xz 
           sudo mv s3deploy /usr/local/bin                                                                             
                                                                                                                       
       - name: Deploy to R2                                                                                            
         env:                                                                                                          
           AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}                                                          
           AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}                                                  
           R2_BUCKET: ${{ secrets.R2_BUCKET_NAME }}                                                                    
           R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}                                                                     
         run: |                                                                                                        
           echo "::group::Deploying to R2"                                                                             
           nix develop --command bash -c '                                                                             
             s3deploy -source="${{ env.WEBSITE_OUTPUT }}/dist" \                                                       
               -bucket="${{ env.R2_BUCKET }}" \                                                                        
               -region="auto" \                                                                                        
               -endpoint="${{ env.R2_ENDPOINT }}" \                                                                    
               -public-access \                                                                                        
               -exclude="/404wolf.com/*" \                                                                             
               -force                                                                                                  
           '                                                                                                           
           echo "::endgroup::"
