name: Build and Deploy to R2                                                                                          
                                                                                                                      
on:                                                                                                                   
  push:                                                                                                               
    branches: [main]                                                                                                  
  workflow_dispatch:                                                                                                  
                                                                                                                      
jobs:                                                                                                                 
  build-and-deploy:                                                                                                   
    runs-on: ubuntu-latest                                                                                            
                                                                                                                      
    steps:                                                                                                            
      - name: Checkout code                                                                                           
        uses: actions/checkout@v3                                                                                     
        with:                                                                                                         
          fetch-depth: 0                                                                                              
                                                                                                                      
      - name: Install Nix                                                                                             
        uses: cachix/install-nix-action@v22                                                                           
        with:                                                                                                         
          nix_path: nixpkgs=channel:nixos-unstable                                                                    
          extra_nix_config: |                                                                                         
            experimental-features = nix-command flakes                                                                
                                                                                                                      
      - name: Build website                                                                                           
        run: |                                                                                                        
          WEBSITE_OUTPUT=$(nix build --print-out-paths)                                                               
          echo "WEBSITE_OUTPUT=$WEBSITE_OUTPUT" >> $GITHUB_ENV                                                        
                                                                                                                      
      - name: Deploy to R2                                                                                            
        env:                                                                                                          
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}                                                          
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}                                                  
          R2_BUCKET: ${{ secrets.R2_BUCKET_NAME }}                                                                    
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}                                                                 
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}                                                                     
        run: |                                                                                                        
          echo "::group::Deploying to R2"                                                                             
          # Create a MIME types file                                                                                  
          cat > mime.types << EOF                                                                                     
          application/javascript js mjs                                                                               
          application/json json                                                                                       
          text/css css                                                                                                
          text/html html htm                                                                                          
          image/svg+xml svg                                                                                           
          image/jpeg jpg jpeg                                                                                         
          image/png png                                                                                               
          image/gif gif                                                                                               
          font/woff woff                                                                                              
          font/woff2 woff2                                                                                            
          font/ttf ttf                                                                                                
          EOF                                                                                                         
                                                                                                                      
          # Configure AWS CLI to use our MIME types                                                                   
          mkdir -p ~/.aws                                                                                             
          cat > ~/.aws/config << EOF                                                                                  
          [default]                                                                                                   
          s3 =                                                                                                        
            mime_types = $(pwd)/mime.types                                                                            
          EOF                                                                                                         
                                                                                                                      
          nix develop --command bash -c '                                                                             
            aws s3 sync "${{ env.WEBSITE_OUTPUT }}/dist" "s3://${{ env.R2_BUCKET }}/" \                               
              --delete \                                                                                              
              --exclude "/media/*" \
              --endpoint-url "${{ env.R2_ENDPOINT }}"                                                                 
          '                                                                                                           
          echo "::endgroup::"
